# Generated by Django 4.1.1 on 2022-10-04 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoraunt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='ingredient3',
        ),
        migrations.AddField(
            model_name='dishes',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), null=True, size=None),
        ),
    ]
