# Generated by Django 4.1.1 on 2022-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoraunt_app', '0002_remove_dishes_ingredient1_remove_dishes_ingredient2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dishes',
            name='ingredients',
            field=models.ManyToManyField(to='restoraunt_app.ingredients'),
        ),
    ]
