# Generated by Django 4.1.1 on 2022-10-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoraunt_app', '0003_remove_dishes_ingredients_dishes_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
