# Generated by Django 4.1.1 on 2022-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoraunt_app', '0004_dishes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.FloatField(),
        ),
    ]
